spring.application.name=gatewayserver
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=unrestricted
spring.cloud.discovery.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.main.web-application-type=reactive
