spring.application.name=backend
spring.profiles.default=dev
# server.port=8000
# server.address=0.0.0.0
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://localhost:5432/java20_jwt
# spring.datasource.username=postgres
# spring.datasource.password=password
# spring.security.user.name=user
# spring.security.user.password=password
# management.endpoints.web.exposure.include=info,health,metrics,loggers,beans,shutdown
# management.endpoint.shutdown.access=unrestricted
# management.info.env.enabled=true
# info.app.name=eCommerce Backend
# info.app.version=1.0.0
# info.app.description=Test Spring Application With Actuator, Grafana, RabitMQ
